import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url));
const luaRoot = join(here, '..', 'lua');

export function readLuaTemplate(name: string): string {
  return readFileSync(join(luaRoot, name), 'utf8');
}

export function writeCaptureScript(dumpDir: string, mode: 'auto' | 'manual', timeoutSec: number): string {
  mkdirSync(dumpDir, { recursive: true });
  const dumpPosix = dumpDir.replace(/\\/g, '/');
  const inputLua = readLuaTemplate('mesen_input.lua');
  const capLua = readLuaTemplate('mesen_capture.lua');
  const body = [
    `-- generated by rhcap1-mesen`,
    `local DUMP_DIR = ${JSON.stringify(dumpPosix)}`,
    `local MODE = ${JSON.stringify(mode)}`,
    `local TIMEOUT_FRAMES = ${Math.max(1, Math.floor(timeoutSec * 60))}`,
    inputLua,
    capLua,
  ].join('\n');
  const out = join(dumpDir, 'rhcap1.lua');
  writeFileSync(out, body);
  return out;
}

export function writeApplyScript(dumpDir: string, wramPath: string, cpuJsonPath: string): string {
  mkdirSync(dumpDir, { recursive: true });
  const apply = readLuaTemplate('mesen_apply.lua');
  const body = [
    `local WRAM_PATH = ${JSON.stringify(wramPath.replace(/\\/g, '/'))}`,
    `local CPU_PATH = ${JSON.stringify(cpuJsonPath.replace(/\\/g, '/'))}`,
    apply,
  ].join('\n');
  const out = join(dumpDir, 'rhapply1.lua');
  writeFileSync(out, body);
  return out;
}
