import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const luaRoot = join(here, '..', 'lua');

export function readLuaTemplate(name: string): string {
  return readFileSync(join(luaRoot, name), 'utf8');
}

export function writeCaptureScript(dumpDir: string, mode: 'auto' | 'manual', timeoutSec: number): string {
  mkdirSync(dumpDir, { recursive: true });
  const dumpPosix = dumpDir.replace(/\\/g, '/');
  const inputLua = readLuaTemplate('mesen_input.lua');
  const capLua = readLuaTemplate('mesen_capture.lua');
  const body = [
    `-- generated by rhcap1-mesen`,
    `local DUMP_DIR = ${JSON.stringify(dumpPosix)}`,
    `local MODE = ${JSON.stringify(mode)}`,
    `local TIMEOUT_FRAMES = ${Math.max(1, Math.floor(timeoutSec * 60))}`,
    inputLua,
    capLua,
  ].join('\n');
  const out = join(dumpDir, 'rhcap1.lua');
  writeFileSync(out, body);
  return out;
}

export interface ApplyScriptPaths {
  mssPath: string;
  wramPath?: string | null;
  vramPath?: string | null;
  cgramPath?: string | null;
  oamPath?: string | null;
  sramPath?: string | null;
  spcPath?: string | null;
  dspPath?: string | null;
  sa1IramPath?: string | null;
  fillramPath?: string | null;
  cpuPath?: string | null;
  setStateLua?: string;
}

function luaStr(v: string | null | undefined): string {
  return v ? JSON.stringify(v.replace(/\\/g, '/')) : 'nil';
}

export function writeBootProbeScript(resultDir: string, timeoutFrames = 600): string {
  mkdirSync(resultDir, { recursive: true });
  const resultPosix = resultDir.replace(/\\/g, '/');
  const probe = readLuaTemplate('mesen_boot_probe_nmi.lua');
  const body = [
    `-- generated by rhboot1 headless NMI probe`,
    `local RESULT_DIR = ${JSON.stringify(resultPosix)}`,
    `local TIMEOUT_FRAMES = ${Math.max(1, Math.floor(timeoutFrames))}`,
    probe,
  ].join('\n');
  const out = join(resultDir, 'rhboot1_nmi_probe.lua');
  writeFileSync(out, body);
  return out;
}

export function writeApplyScript(dumpDir: string, paths: ApplyScriptPaths): string {
  mkdirSync(dumpDir, { recursive: true });
  const apply = readLuaTemplate('mesen_apply.lua');
  const body = [
    `-- generated by rhlaunch1-mesen: single cpuExec restore`,
    `local MSS_PATH = ${luaStr(paths.mssPath)}`,
    `local WRAM_PATH = ${luaStr(paths.wramPath)}`,
    `local VRAM_PATH = ${luaStr(paths.vramPath)}`,
    `local CGRAM_PATH = ${luaStr(paths.cgramPath)}`,
    `local OAM_PATH = ${luaStr(paths.oamPath)}`,
    `local SRAM_PATH = ${luaStr(paths.sramPath)}`,
    `local SPC_PATH = ${luaStr(paths.spcPath)}`,
    `local DSP_PATH = ${luaStr(paths.dspPath)}`,
    `local SA1_IRAM_PATH = ${luaStr(paths.sa1IramPath)}`,
    `local FILLRAM_PATH = ${luaStr(paths.fillramPath)}`,
    `local CPU_PATH = ${luaStr(paths.cpuPath)}`,
    paths.setStateLua || 'local SETSTATE = nil',
    apply,
  ].join('\n');
  const out = join(dumpDir, 'rhapply1.lua');
  writeFileSync(out, body);
  return out;
}
