import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { RhState1 } from '../rhstate1/types.ts';

const luaRoot = join(dirname(fileURLToPath(import.meta.url)), '..', 'lua');

function luaStr(v: string | null | undefined): string {
  return v ? JSON.stringify(v.replace(/\\/g, '/')) : 'nil';
}

function writeBin(dir: string, name: string, data: Uint8Array | null | undefined): string | null {
  if (!data) return null;
  const p = join(dir, name);
  writeFileSync(p, data);
  return p;
}

export interface BizhawkScriptBins {
  wram: Uint8Array;
  vram?: Uint8Array | null;
  cgram?: Uint8Array | null;
  oam?: Uint8Array | null;
  apuram?: Uint8Array | null;
  cpu: RhState1['cpu'];
}

function preamble(dir: string, bins: BizhawkScriptBins): string[] {
  const cpu = bins.cpu;
  return [
    `local WRAM_PATH = ${luaStr(writeBin(dir, 'wram.bin', bins.wram))}`,
    `local VRAM_PATH = ${luaStr(writeBin(dir, 'vram.bin', bins.vram))}`,
    `local CGRAM_PATH = ${luaStr(writeBin(dir, 'cgram.bin', bins.cgram))}`,
    `local OAM_PATH = ${luaStr(writeBin(dir, 'oam.bin', bins.oam))}`,
    `local APURAM_PATH = ${luaStr(writeBin(dir, 'apuram.bin', bins.apuram))}`,
    `local CPU = { a = ${cpu.a}, x = ${cpu.x}, y = ${cpu.y}, d = ${cpu.d}, db = ${cpu.db}, p = ${cpu.p}, sp = ${cpu.sp}, pc = ${cpu.pc}, e = ${cpu.e} }`,
  ];
}

function pokeLua(): string {
  return readFileSync(join(luaRoot, 'bizhawk_poke.lua'), 'utf8');
}

export function writeBizhawkApplyScript(
  dir: string,
  opts: BizhawkScriptBins & { outPath: string },
): string {
  mkdirSync(dir, { recursive: true });
  const tail = readFileSync(join(luaRoot, 'bizhawk_apply.lua'), 'utf8');
  const body = [
    `-- generated by rhstate1-bizhawk`,
    ...preamble(dir, opts),
    `local OUT_PATH = ${luaStr(opts.outPath)}`,
    pokeLua(),
    tail,
  ].join('\n');
  const luaPath = join(dir, 'rhstate1_bizhawk.lua');
  writeFileSync(luaPath, body);
  return luaPath;
}

export function writeBizhawkLaunchScript(
  dir: string,
  opts: BizhawkScriptBins & { connectorPath?: string | null },
): string {
  mkdirSync(dir, { recursive: true });
  const tail = readFileSync(join(luaRoot, 'bizhawk_launch.lua'), 'utf8');
  const connector = opts.connectorPath && existsSync(opts.connectorPath) ? opts.connectorPath : null;
  const body = [
    `-- generated by rhlaunch1-bizhawk`,
    ...preamble(dir, opts),
    `local CONNECTOR_PATH = ${luaStr(connector)}`,
    `pcall(function()`,
    `  client.pause()`,
    `end)`,
    pokeLua(),
    tail,
  ].join('\n');
  const luaPath = join(dir, 'rhlaunch1_bizhawk.lua');
  writeFileSync(luaPath, body);
  return luaPath;
}

export function resolveBizhawkPath(): string | null {
  const p = process.env.BIZHAWK_PATH;
  if (p && existsSync(p)) return p;
  return null;
}

export function bizhawkLooksPresent(): boolean {
  return resolveBizhawkPath() != null;
}
