import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { RhState1 } from '../rhstate1/types.ts';

const luaRoot = join(dirname(fileURLToPath(import.meta.url)), '..', 'lua');

function luaStr(v: string | null | undefined): string {
  return v ? JSON.stringify(v.replace(/\\/g, '/')) : 'nil';
}

function writeBin(dir: string, name: string, data: Uint8Array | null | undefined): string | null {
  if (!data) return null;
  const p = join(dir, name);
  writeFileSync(p, data);
  return p;
}

export function writeBizhawkApplyScript(
  dir: string,
  opts: {
    outPath: string;
    wram: Uint8Array;
    vram?: Uint8Array | null;
    cgram?: Uint8Array | null;
    oam?: Uint8Array | null;
    apuram?: Uint8Array | null;
    cpu: RhState1['cpu'];
  },
): string {
  mkdirSync(dir, { recursive: true });
  const template = readFileSync(join(luaRoot, 'bizhawk_apply.lua'), 'utf8');
  const cpu = opts.cpu;
  const body = [
    `-- generated by rhstate1-bizhawk`,
    `local WRAM_PATH = ${luaStr(writeBin(dir, 'wram.bin', opts.wram))}`,
    `local VRAM_PATH = ${luaStr(writeBin(dir, 'vram.bin', opts.vram))}`,
    `local CGRAM_PATH = ${luaStr(writeBin(dir, 'cgram.bin', opts.cgram))}`,
    `local OAM_PATH = ${luaStr(writeBin(dir, 'oam.bin', opts.oam))}`,
    `local APURAM_PATH = ${luaStr(writeBin(dir, 'apuram.bin', opts.apuram))}`,
    `local OUT_PATH = ${luaStr(opts.outPath)}`,
    `local CPU = { a = ${cpu.a}, x = ${cpu.x}, y = ${cpu.y}, d = ${cpu.d}, db = ${cpu.db}, p = ${cpu.p}, sp = ${cpu.sp}, pc = ${cpu.pc}, e = ${cpu.e} }`,
    template,
  ].join('\n');
  const luaPath = join(dir, 'rhstate1_bizhawk.lua');
  writeFileSync(luaPath, body);
  return luaPath;
}

export function resolveBizhawkPath(): string | null {
  const p = process.env.BIZHAWK_PATH;
  if (p && existsSync(p)) return p;
  return null;
}

export function bizhawkLooksPresent(): boolean {
  return resolveBizhawkPath() != null;
}
